/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Book: typeof import('./components/Book.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    CardImageEffect: typeof import('./components/CardImageEffect.vue')['default']
    CardImageMutation: typeof import('./components/CardImageMutation.vue')['default']
    CardPopup: typeof import('./components/CardPopup.vue')['default']
    ChallengesList: typeof import('./components/ChallengesList.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MisRepetidasDrawer: typeof import('./components/MisRepetidasDrawer.vue')['default']
    Page: typeof import('./components/Page.vue')['default']
    StatsCardCounter: typeof import('./components/StatsCardCounter.vue')['default']
    SwaggerPage: typeof import('./components/SwaggerPage.vue')['default']
    Tokens: typeof import('./components/Tokens.vue')['default']
    TokensCounter: typeof import('./components/TokensCounter.vue')['default']
  }
}
